apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus
  name: nexus
  namespace: default
  selfLink: /api/v1/namespaces/default/services/nexus

spec:
  ports:
    - name: http
      port: 80
      targetPort: 8081
    - name: docker
      port: 5000
      targetPort: 5000
  selector:
    app: nexus
  type: NodePort
