apiVersion: v1
kind: Service
metadata:
  labels:
    app: nexus-official
  name: nexus-official
  namespace: default
  selfLink: /api/v1/namespaces/default/services/nexus-official

spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8081
    - name: docker
      port: 5001
      targetPort: 5000
  selector:
    app: nexus-official
  type: NodePort
